--CREACION DE BASE DE DATOS EN LINUX

-- $ Sqlite3 EOD.db

--CREACION DE BASE DE DATOS SQLITE

/*

CREATE TABLE SIGINTUSER (
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME TEXT NOT NULL,
   LASTNAME TEXT NOT NULL,
   USEREOD CHAR 6 NOT NULL,
   KEYEOD TEXT NOT NULL
);

CREATE TABLE EXPLOSIVE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CATEGORY TEXT NOT NULL,
    NAMEXPLO TEXT NOT NULL,
    IMAGEXPLO BLOB NOT NULL,
    DESCRIEXPLO TEXT NOT NULL 
);

*/

